### ISSUE TITLE
Heartbeat logs?

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-miner#2]
Just thought it might be useful to have a temporary log output in balena saying "connection ok" or something, and then expose that on the dashboard and the local diagnostics page perhaps - like miner connection ok type of thing

**Comment by ryanteck** [comment]
The logs are semi limited to what Helium provide. 

However what I can do is add data from the miner to the Diagnostics page which will contain more detailed info. (Height, Connection, Etc)

**Comment by ryanteck** [comment]
Moving mostly to https://github.com/NebraLtd/hm-diag/issues/35

**Comment by shawaj** [comment]
Yeah sounds like a good idea. The only thing I was thinking would be for it to auto-diagnose and fix issues where possible. As the Helium miner seems a bit buggy...

Just thought some error handling and more info to help us find issues would be good

**Comment by shawaj** [comment]
Was speaking with Kevin and thought maybe we could output some of the miner error logs somewhere in the diagnostics page
