### ISSUE TITLE
AU915 all witnessing invalid - wrong region

### ISSUE THREAD

**Issue by cryptowinteam** [NebraLtd/hm-miner#26]
Since last update it would appear that all Nebra units in Australia are getting this invalid witness message.  This appears to be a new issue as this message has not been seen before and the recent update to incorrect frequency in AU915 is very probable to be the cause.

![image](https://user-images.githubusercontent.com/83017637/133599611-f43d9b31-6503-4374-bcee-15a605d0d6ff.png)

**Comment by vpetersson** [comment]
Closed in favor of https://github.com/NebraLtd/hm-pktfwd/issues/51
