### ISSUE TITLE
Add Nebra version to lsb_release payload

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-miner#47]
We want to track both the Nebra and upstream Helium version. We just need to modify [this line](https://github.com/NebraLtd/hm-miner/blob/master/Dockerfile#L13) to complete it with whatever payload we want to include.

Suggested format: `"$HELIUM_GA_RELEASE ($GIT_HASH)`

**Comment by shawaj** [comment]
Don't think we need this anymore as it's covered by the firmware hash in the docker-compose as well as the main version number
