### ISSUE TITLE
Update config snap_source_base_url variable

### ISSUE THREAD

**Issue by dowjames** [NebraLtd/hm-miner#48]
Seems like snap_source_base_url has changed to s3_base_url in the miner application. Therefore quicksync is currently broken producing the snapshot download or loading failed because {error,no_s3_base_url} error.

Please update the https://helium-assets.nebra.com/docker.config to reflect this change.

**Comment by vpetersson** [comment]
No, it's the other way around. See [this post](https://engineering.helium.com/2021/10/27/blockchain-release-auto-snaps-and-bug-fixes.html). Helium released a breaking change in 2021.10.27.0 and changed s3_base_url to snap_source_base_url. We're still working on updating our system to reflect all these breaking changes.

**Comment by dowjames** [comment]
Yes, you're right. The result is still the same though ;)

**Comment by vpetersson** [comment]
@dowjames The latest GA was deployed about an hour ago, so that should be resolved.

**Comment by dowjames** [comment]
@vpetersson Seems to be resolved, yes. Thanks
