### ISSUE TITLE
Outdoor miner firmware stuck

### ISSUE THREAD

**Issue by prandash** [NebraLtd/hm-miner#49]
I have a miner at 200 feet on a tower. Saying it is still loading firmware is 2021.08.11.2 how do I get firmware updated?
![Screenshot_20211109-162851](https://user-images.githubusercontent.com/88388991/141352787-5f96c37e-5dbb-44ef-9beb-a06d1fad1a50.jpg)

**Comment by shawaj** [comment]
Please email support@nebra.com

**Comment by prandash** [comment]
I did three weeks ago
