### ISSUE TITLE
Local Diagnostics Page and Green Light Connectivity Broken

### ISSUE THREAD

**Issue by badaczewski** [NebraLtd/hm-miner#52]
Multiple users are reporting local diagnostic pages displaying only "Internal Server Error" as well as no connectivity after attempted reboots ("No green light").

**Comment by vpetersson** [comment]
This is not a support forum. Please contact support@nebra.com

**Comment by shawaj** [comment]
Fixed already in https://github.com/NebraLtd/hm-diag/pull/212
