### ISSUE TITLE
Rework snapshot generation

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-miner#6]
Currently, the [snapshot-bumper](https://github.com/NebraLtd/vps-scripts/tree/master/snapshot-bumper) is running on a VPS. We need to do a few changes to this:

* Rewrite the code base
* Make it run in a GitHub Action using [on.schedule](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule) hourly (or similar)
* Generate the new `docker.config` and copy it to GCP or similar automatically

**Comment by robputt** [comment]
https://github.com/NebraLtd/hm-block-tracker/pull/1

**Comment by shawaj** [comment]
@robputt on the above linked PR/repo it says 

> After discussion with Helium core team it appears we do not need to maintain our own S3 repository with snapshots, they already provide a public repository for snapshots which vendors can utilise, see https://snapshots.helium.wtf/mainnet/snap-<block_height>.

Do you know how frequently this is updated? Presumably it's only when a new blessed block is released?

**Comment by robputt** [comment]
<img width="1088" alt="Screenshot 2021-07-13 at 07 34 14" src="https://user-images.githubusercontent.com/6697027/125402823-bf66d680-e3ac-11eb-84fd-2b37f7502d02.png">

@shawaj looks like it is more frequent than this, according to Hakeem there is also some API where you can query snapshot data. Asking for more info as it's not documented at docs.helium.com

**Comment by robputt** [comment]
<img width="1073" alt="Screenshot 2021-07-13 at 07 41 33" src="https://user-images.githubusercontent.com/6697027/125403749-c510ec00-e3ad-11eb-8ec7-af0ff3501a3c.png">

**Comment by robputt** [comment]
https://github.com/NebraLtd/hm-block-tracker/pull/4

**Comment by robputt** [comment]
I think this is done.

- Uses upstream blessed block and snapshots
- Dynamically builds docker.config via CI every hour and publishes to Google Cloud Storage
