### ISSUE TITLE
Blockchain storage limit ENV variable

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-miner#62]
See here

https://github.com/helium/blockchain-core/pull/808/
Supersedes: https://github.com/NebraLtd/hm-dashboard/issues/759

**Acceptance Criteria**
- `BLOCKCHAIN_ROCKSDB_GC_BYTES`:  8GB (bytes!)
- `blocks_to_protect_from_gc`: 6000

**Comment by shawaj** [comment]
https://engineering.helium.com/2021/12/30/blockchain-release-snapshot-loading-and-storage-improvements.html

**Comment by shawaj** [comment]
@SebastianMaj  FYI I think the blocks to protect thing needs to go in sys.config (hm-block-tracker) not as an ENV variable

**Comment by shawaj** [comment]
Also of note is:

> The last 100k of blocks and snapshots are protected from GC.

In https://github.com/helium/blockchain-core/pull/808

I guess this is just the default but I wonder if 6000 blocks is too little. We should enquire with Helium I think

**Comment by SebastianMaj** [comment]
> Also of note is:
> 
> > The last 100k of blocks and snapshots are protected from GC.
> 
> In [helium/blockchain-core#808](https://github.com/helium/blockchain-core/pull/808)
> 
> I guess this is just the default but I wonder if 6000 blocks is too little. We should enquire with Helium I think

That would be a good thing to clarify with them just to be safe considering their value is so high. What would be the best way to contact them about this?

**Comment by shawaj** [comment]
@marvinmarnold has them on the internal/external channel on the Helium Discord.

Alternatively maybe just a comment on the github? 

But the Discord probably quicker

**Comment by shawaj** [comment]
@SebastianMaj @marvinmarnold I think that 100k might be a typo there. The code seems to say 10k as the default, unless I'm mistaken:

https://github.com/helium/blockchain-core/blob/3cd6bca6c5595a1363a9bbd625ef254383a4141b/src/blockchain.erl#L1988

**Comment by shawaj** [comment]
Last but not least, it seems that BLOCKCHAIN_ROCKSDB_GC_BYTES should only be set when we need to prune the storage, and it prunes it by at least the amount of bytes we face requested.

I'm not sure what happens if you have it set permanently or whether that will cause issues?

But perhaps it could just be set on a schedule if it's not good for it to be set permanently.

In any case, worth investigating further

**Comment by marvinmarnold** [comment]
The current documentation says 10k, they must have updated. I'll reach out on Discord and get some input too.

![Screen Shot 2022-01-18 at 3 10 25 PM](https://user-images.githubusercontent.com/1311030/150019455-e302a724-8241-4505-80ce-1e7b46dde5e5.png)

**Comment by shawaj** [comment]
Yeah maybe it's 10k then. Worth checking this and whether we can just set and further the environment variable rather than only setting it when we need to prune it

**Comment by shawaj** [comment]
Reply here looks like 6k will be fine https://github.com/helium/blockchain-core/pull/808#issuecomment-1015938490

**Comment by marvinmarnold** [comment]
Via discord, 2k a possible min.

![Screen Shot 2022-01-18 at 6 56 52 PM](https://user-images.githubusercontent.com/1311030/150043518-fdb7a289-2809-4f04-a7f6-ff2e83d84ae4.png)

**Comment by shawaj** [comment]
> Via discord, 2k a possible min.
> 
> ![Screen Shot 2022-01-18 at 6 56 52 PM](https://user-images.githubusercontent.com/1311030/150043518-fdb7a289-2809-4f04-a7f6-ff2e83d84ae4.png)

Yeah same on the other link @marvinmarnold - wonder if 5k is best just to be safe.

How big is the average block in bytes I wonder?

**Comment by vpetersson** [comment]
I've manually set this variable on TestNet. Kevin is monitoring the situation.
