### ISSUE TITLE
Load correct sysconfigs for Bobcat

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-miner#65]
ECC is 608 but may be connected on different bus

https://github.com/NebraLtd/hm-miner/blob/4cfcfedc7929386a98068c553aebe8b2cedc3dfc/start-miner.sh#L12

**Comment by shawaj** [comment]
could also be same bus but different address on bus...which is something we have not handled in hm-pyhelper yet in fact

**Comment by vpetersson** [comment]
@marvinmarnold this can be closed out, right?

**Comment by marvinmarnold** [comment]
This is under the Bobcat epic. I changed the title to be more clear.
