### ISSUE TITLE
Miner frequently rebooting

### ISSUE THREAD

**Issue by PureTek-Innovations** [NebraLtd/hm-miner#66]
My miner, Nebra Outdoor Hotspot Gen 1, running firmware 2022.01.04.0 appears to be frequently rebooting.
Others seem to be having similar issues.

This is a continuation of issue #64 
[https://github.com/NebraLtd/hm-miner/issues/64](url)

**Comment by KevinWassermann94** [comment]
This is not a support channel send a mail so sales@nebra.com

**Comment by PureTek-Innovations** [comment]
@KevinWassermann94 GitHub issues are normally used for reporting software problems.
This appears to be a software problem
