### ISSUE TITLE
Load correct sysconfig for RAK

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-miner#67]

**Comment by shawaj** [comment]
@marvinmarnold the RAK works already with the standard RasPi config doesn't it?

**Comment by vpetersson** [comment]
@shawaj Possibly yeah. We just want to create 'template tasks' for enabling new hardware so we have good step-by-step tasks.

**Comment by MuratUrsavas** [comment]
Checked the required steps and seen that it is compatible with our default `sys.config`. Right now we're dealing with LoRa stage issues, but this is not related to this topic. We can close this issue as Done.

**Comment by vpetersson** [comment]
Yeah feel free to close this out.
