### ISSUE TITLE
Capture the Helium Miner logs

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-miner#70]
The Miner software stores its logs in `/var/log/miner`. There are various tidbits in there that would have been very useful for diagnostic purposes as it's currently wiped when the miner is restarted (or is killed by OOM).

In a perfect world, I'd like to send these logs to something like Logtail (that we use for HTP logging) so that we can better diagnose and coordinate these logs.

One way to do this is to perhaps to simply add a final line to the `Dockerfile` that will execute after the miner is killed that would suck up all those log files and send them to Logtail.

An alternative approach would be to log them to persistent storage, and perhaps use another container to submit these logs to a central logging repository.

Open questions:
- What is the memory footprint of vector?
- Is rate limiting a constraint?

Acceptance criteria
- Logs written to Logtail, to single source for all services
- Miner container writes logs to centralized logging
- Create hm-log-shipper to contain this work
- Ensure daily logs per device doesn't exceed 10MB
- Logs must include metadata about: hostname, frequency, fleet, service, animal name, balena ID, eth MAC

**Comment by marvinmarnold** [comment]
[Google IoT Core](https://cloud.google.com/iot-core) might get us a lot out of the box and Balena already has some tooling for it: https://www.balena.io/docs/learn/develop/integrations/google-iot/

**Comment by vpetersson** [comment]
I wouldn't use Core IoT for sending general logs though. It's great for pub/sub event streams, but sending logs this way will be extremely expensive.

**Comment by vpetersson** [comment]
[Vector](https://vector.dev/docs/reference/configuration/) looks promising. We could in theory run this in a separate container and suck up logs from various containers (hm-diag, hm-miner, hm-config etc) such that we have a single place to log to.

**Comment by marvinmarnold** [comment]
Nice, Vector is from Datadog and I was looking at Datadog for bandwidth tracking too but didn't make much progress. Having a separate container makes sense. Could be the same at the watchdog too.

BTW, are you worried about transfer or storage costs on Google for logs? Or both?

**Comment by vpetersson** [comment]
> BTW, are you worried about transfer or storage costs on Google for logs? Or both?

I was mostly worried about the data volume, but having looked at the [latest prices](https://cloud.google.com/iot/pricing), maybe it isn't too bad.

**Comment by vpetersson** [comment]
I started looking at this and it appears as we already have persistent storage on miner logs through [named-volumes](https://www.balena.io/docs/learn/develop/multicontainer/#named-volumes). 

* We create a named volume called [miner-logs](https://github.com/NebraLtd/helium-miner-software/blob/master/templates/docker-compose.template#L103)
* This volume is then [mapped against](https://github.com/NebraLtd/helium-miner-software/blob/master/templates/docker-compose.template#L50) `/var/log/miner`

As such, we should in theory have persistent miner logs already.
